### ISSUE TITLE
Buy domain

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [meterlytics/meterlytics.com#4]
@lnmunhoz after we decide a better new project name, I will buy a domain for it.
For while these domains are free:
marsmetric.com (free)
marsmetric.org (free)
marsmetrics.com (free)
marsmetrics.org (free)
marslytics.com (free)
marslytics.org (free)
rocketmetrics.org (free)
**metriclytics.com (not free)**
**rocketmetrics.com (free, but too expensive R$ 13k)**
**rocketlytics.com (not free)**

**Comment by caio-ribeiro-pereira** [comment]
@lnmunhoz I liked the **marsmetrics.com** and you?

**Comment by lnmunhoz** [comment]
What about sputlytics? [from sputnik satellite](https://pt.wikipedia.org/wiki/Sputnik)

**Comment by caio-ribeiro-pereira** [comment]
@lnmunhoz nice name! and it's available to buy it!

**Comment by caio-ribeiro-pereira** [comment]
sputlytics.com is free and there is a curious domain sputlytics.space for R$ 7,99

**Comment by lnmunhoz** [comment]
Found this illustration. Fun logo :)
![sputnik](https://cloud.githubusercontent.com/assets/4376835/13749483/612c2b2c-e9e0-11e5-800d-9fd7af5f9a16.png)

**Comment by caio-ribeiro-pereira** [comment]
Done! Now we have **sputlytics.com**
